# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrv', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Building')),
            ],
        ),
        migrations.CreateModel(
            name='SingleResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student_ID', models.CharField(max_length=12)),
                ('temp', models.CharField(choices=[(b'HH', b'Very Hot!'), (b'OH', b'Warm'), (b'OO', b'Just right!'), (b'OC', b'Cool'), (b'CC', b'Very Cold!')], max_length=2)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Building')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Room')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
