# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170920_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleresponse',
            name='room',
            field=models.PositiveIntegerField(),
        ),
    ]
