# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 07:05
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170927_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='building',
            name='geom',
            field=djgeojson.fields.PointField(default=0),
            preserve_default=False,
        ),
    ]
