# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20171005_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='temp',
            field=models.FloatField(default=0),
        ),
    ]
