# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_building_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blurb', models.TextField()),
                ('image', models.ImageField(upload_to=b'')),
                ('geom', djgeojson.fields.PointField()),
            ],
        ),
    ]
