# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20171019_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodPost',
        ),
    ]
