# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20171227_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleresponse',
            name='student_ID',
        ),
    ]
