# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-10 20:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180607_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodresponse',
            name='building',
        ),
        migrations.RemoveField(
            model_name='foodresponse',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='foodresponse',
            name='room',
        ),
        migrations.AddField(
            model_name='foodresponse',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 1800)),
        ),
        migrations.AddField(
            model_name='foodresponse',
            name='location',
            field=djgeojson.fields.PointField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodresponse',
            name='food',
            field=models.TextField(blank=True, null=True),
        ),
    ]
