# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-11 05:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20180610_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodresponse',
            name='duration',
        ),
        migrations.AddField(
            model_name='foodresponse',
            name='building',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodresponse',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 10, 22, 8, 17, 568819)),
            preserve_default=False,
        ),
    ]
